### ISSUE TITLE
Various issues about this marked adaptor for deno

### ISSUE THREAD

**Issue by jingkaimori** [prettykool/marked-deno#1]
there are several issues about this repo
* marked provided ESM version file
* `marked.min.js` is UMD version, so it's impossible to use current definition, or re-export them in `deps.ts`
* marked has a type definition file at `@types/marked`

I use those declaration to introduce marked with its type information:

```typescript
// @deno-types="https://cdn.jsdelivr.net/npm/@types/marked@4.0.7/index.d.ts"
export * from "https://cdn.jsdelivr.net/npm/marked@4.2.3/lib/marked.esm.js";
```

**Comment by prettykool** [comment]
Very good insight that I, admittedly, should've checked on when I initially made this. It's been updated as such (See [201a07b](https://github.com/prettykool/marked-deno/commit/201a07b1820b3b7b503af12e8235bb3bbe400c5f), [c39bd6f](https://github.com/prettykool/marked-deno/commit/c39bd6f570683add8c278eef685c6d3da16e085c)), and, hopefully, no further problems should arise (Although feel free to tell me if something goes horribly wrong)

I'll be closing this. Thanks for your efforts.
