### ISSUE TITLE
Marked uses typescript since 6.0.0

### ISSUE THREAD

**Issue by jingkaimori** [prettykool/marked-deno#2]
`@types/marked` package stay at version 5.0.0, newer version of Marked is developed with typescript, so this package should be re-worked

**Comment by prettykool** [comment]
Thanks for letting me know about this - Wouldn't have caught my attention otherwise. I've updated the package accordingly, and as of [1.0.2](https://github.com/prettykool/marked-deno/releases/tag/1.0.2), the problem should be fixed. Let me know if there's any problems you come across.

**Comment by jingkaimori** [comment]
Confirmed that npm package works, close this issue
